openapi: 3.0.0
info:
  title: Item API
  description: Simple API to manage items
  version: 1.0.0
paths:
  /items:
    get:
      summary: Retrieve all items
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    quantity:
                      type: integer
    post:
      summary: Add an item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                quantity:
                  type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
